version: '3'
services:
    ecommerce:
        container_name: ecommerce
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8000:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        command: "chmod +x ./deploy.sh && ./deploy.sh"

    node:
        image: node:20-alpine
        container_name: node
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        command: "npm install && npm run dev"
        depends_on:
            - ecommerce
